apiVersion: v1
kind: Pod
metadata:
  name: test-pvc-consumer
  namespace: default
spec:
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: pg-cluster-amen-api-3580661146-restore-815490-1
  containers:
    - name: test
      image: busybox
      command: ["sleep", "3600"]
      volumeMounts:
        - mountPath: "/data"
          name: data
